services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    environment:
      GOMODCACHE: /go/src/app/.modcache
      GOCACHE: /go/src/app/.cache
    env_file:
      - .env.prod
    volumes:
      - "./:/go/src/app"
    ports:
      - "8080:8080"
