FROM golang:1.21.0

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV APP_ENV=production

COPY .env.prod .env

WORKDIR /app/cmd/http

RUN go build -o /app/main ./...

EXPOSE 8080

CMD ["/app/main"]