services:
  app:
    build:
      context: .
    container_name: app
    environment:
      GOMODCACHE: /go/src/app/.modcache
      GOCACHE: /go/src/app/.cache
    env_file:
      - .env.dev
    volumes:
      - "./:/go/src/app"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env.dev
    volumes:
      - "./.service-db:/var/lib/mysql"
    ports:
      - "3333:3306"

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "./.redis-data:/data"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
